version: "3"

networks:
  default:
    external:
      name: dnm

services:
  admin:
    image: apache/dubbo-admin
    container_name: dubbo-admin
    restart: always
    environment:
      - admin.registry.address=zookeeper://172.172.0.50:2181
      - admin.config-center=zookeeper://172.172.0.50:2181
      - admin.metadata-report.address=zookeeper://172.172.0.50:2181
    networks:
      default:
        ipv4_address: "172.172.0.60"
